services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  redis:
    image: redis
    container_name: redis
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: Urlbackend
    env_file: ./backend/.env
    ports: 
      - "5000:5000"
    depends_on:
      - mongo
      - redis
    networks:
      - app-network


  frontend:
    build: ./frontend
    container_name: Urlfrontend
    env_file: ./frontend/.env
    ports:
      - "5173:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge


